#!/bin/bash

docker run -d --name database -p 3306:3306 -e MYSQL_ROOT_PASSWORD=alesaudate -e MYSQL_DATABASE=vagas mysql:5.7.24
sleep 10
docker rm app || true
docker run -d --name app -p 9000:9000 --link database:database alesaudate/vagas
